<!DOCTYPE html>
<html>
<head>
<title>Share</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?= $this->fetch('layout-styles') ?>
<style>

body { font-family: Arial, sans-serif; }
a { text-decoration: none; }
table { border-collapse: collapse; }
td { padding: 0; }

.app-container { margin: 0 auto; max-width: 1280px; }
.table-view th span { font-size: 0.6em; }
.table-view { overflow: auto; }
.table-view tr:nth-child(even) { background-color: #f2f2f2; }

nav.primary-navigation {
    float: left;
    width: 200px;
}
nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
}
nav li {
}
main {
    margin-left: 200px;
}

@media only screen and (max-width: 768px) {
    nav {
        float: none;
    }
    main {
        margin-left: 0;
    }
}

</style>
</head>
<body>
<div class="app-container">
    <header>
        asdf
    </header>
    <nav class="primary-navigation">
        <ul>
            <li><a href="<?= $this->routeUrl('/') ?>">Home</a></li>
            <?php if ($this->app->user()->loggedIn()): ?>
                <?php if ($this->app->user()->current('admin')): ?>
                    <li><a href="<?= $this->routeUrl('/users') ?>">Users</a></li>
                <?php endif ?>
                <li><a href="<?= $this->routeUrl('/settings') ?>">Settings</a></li>
                <li><a href="<?= $this->routeUrl('/logout') ?>">Logout</a></li>
            <?php else: ?>
                <li><a href="<?= $this->routeUrl('/sign-up') ?>">Sign up</a></li>
                <li><a href="<?= $this->routeUrl('/login') ?>">Login</a></li>
            <?php endif ?>
        </ul>
    </nav>
    <main>
        <?= $this->block('content') ?>
    </main>
</div>
<?= $this->fetch('layout-scripts') ?>
<?= $this->block('scripts') ?>
</body>
</html>