<?php $this->startBlock('content') ?>
<h1>Users</h1>
<?php if ($message): ?>
    <div><?= $message['text'] ?></div>
<?php endif ?>
<a href="<?= $this->routeUrl('/user-add') ?>">Add</a>
<form action="<?= $this->routeUrl('/users') ?>" method="get">
    <?php if (!$this->app->config(\Dynart\Micro\App::CONFIG_USE_REWRITE)): ?>
        <input type="hidden" name="route" value="/users">
    <?php endif ?>
    <?= $this->fetch('form', ['form' => $form]) ?>
</form>
<?= $this->fetch('pager', ['pager' => $pager]) ?>
<?= $tableView->fetch() ?>
<?= $this->fetch('pager', ['pager' => $pager]) ?>
<?php $this->endBlock() ?>