<?php $this->startBlock('content') ?>
<h1>Users</h1>
<?php if ($message): ?>
    <div><?= $message['text'] ?></div>
<?php endif ?>
<a href="<?= route_url('/user-add') ?>">Add</a>
<form action="<?= route_url('/users') ?>" method="get">
    <?php if (!use_rewrite()): ?>
        <input type="hidden" name="route" value="/users">
    <?php endif ?>
    <?= $this->fetch('form', ['form' => $form]) ?>
</form>
<?= $this->fetch('pager', ['pager' => $pager]) ?>
<?= $tableView->fetch() ?>
<?= $this->fetch('pager', ['pager' => $pager]) ?>
<?php $this->endBlock() ?>